# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 23:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evidence', '0004_evidence_image_name'),
        ('Disease', '0002_auto_20171225_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_of_belief', models.PositiveIntegerField(default=0, help_text='The measure of belief (percentage) that a disease is present given this evidence exists', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('measure_of_disbelief', models.PositiveIntegerField(default=0, help_text='The measure of disbelief (percentage) that a disease is present given an evidence does not exists', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('archived', models.BooleanField(default=False)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='Disease.Disease')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='Evidence.Evidence')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set([('disease', 'evidence')]),
        ),
    ]
