# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0002_auto_20180110_0321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RulesEvidence',
            new_name='Rules_Evidence',
        ),
    ]
