# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0005_auto_20180112_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='Conjuction_or_Disjunction_Order',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
