# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0009_auto_20180113_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Condition_Order',
            field=models.CharField(default=None, help_text="This field will be the basis of the condition's hierarchy/order, If two or more evidence exists in a rule.<br/>  This statement only accepts the corresponding 'evidence number', an 'or' (disjunction), and an 'and' (conjuction).<br/> e.g. 24 and 34", max_length=500),
        ),
    ]
