# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 22:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0012_auto_20180113_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='Condition_Order',
            field=models.CharField(blank=True, default=None, help_text="This field will be the basis of the condition's hierarchy/order, If two or more evidence exists in a rule.<br/>  This statement only accepts the corresponding 'evidence number', parenthesis , an 'or' (disjunction), and an 'and' (conjuction).<br/> e.g. 24 and 34<br/> **Ignore this if you have only one evidence in a rule.", max_length=500),
        ),
        migrations.AlterField(
            model_name='rule',
            name='measure_of_belief',
            field=models.PositiveIntegerField(default=0, help_text='The measure of belief (percentage) that a disease is present given these evidence exists', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rule',
            name='measure_of_disbelief',
            field=models.PositiveIntegerField(default=0, help_text='The measure of disbelief (percentage) that a disease is present given these evidence does not exists', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
