# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 16:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0015_auto_20180129_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules_Evidence',
            new_name='RulesEvidence',
        ),
        migrations.AlterField(
            model_name='rule',
            name='Condition_Order',
            field=models.CharField(blank=True, default=None, help_text="This field will be the basis of the condition's                     hierarchy/order, If two or more evidence exists in a rule.<br/>  This statement only accepts the corresponding                     'evidence number', parenthesis , an 'or' (disjunction),                     and an 'and' (conjuction).<br/> e.g. 24 and 34<br/> **Ignore this if you have only one evidence in a rule.", max_length=500),
        ),
        migrations.AlterField(
            model_name='rule',
            name='certainty_factor',
            field=models.PositiveIntegerField(default=0, help_text='This ranges from -100 to 100.                      <br/> Positive values means that the evidence confirms or                     supports the disease.                      <br/> Negative values means that the evidence does                      not support the disease.', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
