# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 19:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rules', '0017_auto_20180207_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='certainty_factor',
            field=models.FloatField(default=0, help_text='This ranges from -100 to 100.                      <br/> Positive values means that the evidence confirms or                     supports the disease.                      <br/> Negative values means that the evidence does                      not support the disease.', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
