# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='advise',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
