# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disease', '0002_auto_20171225_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
