# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('Observable Evidence', 'Observable Evidence'), ('Causes', 'Causes')], default='Observable Evidences', max_length=20),
        ),
    ]
