# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0004_evidence_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='image_name',
            new_name='image_path',
        ),
    ]
