# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-20 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0005_auto_20180114_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='evidence_type',
        ),
    ]
