# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0006_remove_evidence_evidence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='image_path',
            field=models.ImageField(blank=True, default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
