# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evidence', '0008_evidence_linked_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='linked_disease',
            field=models.ForeignKey(blank=True, help_text='if an evidence is also a disease, please link it here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_disease', to='Disease.Disease'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='question',
            field=models.CharField(blank=True, help_text="if you have a linked disease this field isn't required.", max_length=500, null=True),
        ),
    ]
